services:
  frontend:
    build: &default-build
      context: ../
      dockerfile: ./frontend/Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION}      # Gives control and is expanded in the starter service
    init: true                              # Need to run as PID 1 to handle os signals like SIGTERM to use Watch correctly
    environment: &default-environment
      NODE_ENV: development
    ports: 
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./node_modules:/app/node_modules
    pull_policy: build
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "${FRONTEND_PORT}"]
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - Dockerfile*
            - compose*.yaml
            - .*ignore
            - .env*
        - action: rebuild
          path: ./package.json

  # Bundler/Starter
  create:
    build: 
      <<: *default-build
      target: base                        # Special Docker build stage
    environment: *default-environment
    volumes:                              # It needs access to the service root dir
      - ./:/app
    command: ["sh", "-c", "npx create-vite . && cd . && npm install"]
    profiles:
      - starter

  npm:                                   # Wrap around npm to use it inside the container
    build:
      <<: *default-build
      target: base
    volumes:
      - ./:/app
    entrypoint: ["npm"]
    command: ["--version"]
    profiles:
      - tooling