#!/bin/bash

# Config environment
# export COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml
# export COMPOSE_PROFILES=tooling
# export COMPOSE_ENV_FILES=.env.envfile1, .env.envfile2
export COMPOSE_ENV_FILES=../.env,../.env.dev.local
# COMPOSE_PROJECT_NAME=my_project

# Default target
function help() {
    echo "Usage: $0 [target]"
    echo ""
    echo "Targets:"
    echo "  create            Create the project"
    echo "  up                Start the development server"
    echo "  npm               Run NPM commands inside Docker"
    echo "                    Run any Docker Compose command"
    echo ""
}

# Helper function to find package-lock.json
function find_package_lock_json() {
    find ./ -maxdepth 3 -name "package-lock.json" | grep -q "package-lock.json"
}

# Target to create the project
function create() {
    if ! find_package_lock_json; then
        echo "Creating project..."
        docker compose run --rm create
    fi
}

# Target to start the development server
function up() {
    create
    echo "Starting development server..."
    docker compose up "$@"
}

# Target to run NPM commands inside Docker
function npm() {
    docker compose run --quiet-pull --rm npm "$@"
}

# Main script logic
case "$1" in
--help)
    help
    ;;
create)
    create
    ;;
up)
    shift
    up "$@"
    ;;
npm)
    shift
    npm "$@"
    ;;
*)
    shift
    docker compose "$@"
    ;;
esac
