#!/bin/bash

# Config environment
# export COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml
# export COMPOSE_PROFILES=tooling
# export COMPOSE_ENV_FILES=.env.envfile1, .env.envfile2
export COMPOSE_ENV_FILES=../.env,../.env.dev.local
# COMPOSE_PROJECT_NAME=my_project

# Default target
function help() {
    echo "Usage: $0 [target]"
    echo ""
    echo "Targets:"
    echo "  create            Create the project"
    echo "  dev               Start the development server"
    echo "  npm               Run NPM commands inside Docker"
    echo "                    Any docker compose command"  
}

# Helper function to find package-lock.json
function find_package_lock_json() {
    find ./ -maxdepth 3 -name "package-lock.json" | grep -q "package-lock.json"
}

# Target to create the project
function create() {
    if ! find_package_lock_json; then
        echo "Creating project..."
        docker compose run --rm create
    fi
}

# Target to start the development server
function dev() {
    create
    echo "Starting development server..."
    docker compose up --watch
}

# Target to run NPM commands inside Docker
function npm() {
    docker compose run --rm npm "$@"
}

# Target to run custom Docker Compose commands
function docker-compose() {
  docker compose "$@"
}

# Main script logic
case "$1" in
    --help)
        help
        ;;
    create)
        create
        ;;
    dev)
        dev
        ;;
    npm)
        shift
        npm "$@"
        ;;
    *)
        shift
        docker-compose "$@"
        ;;
esac
